### PR TITLE
populating app_id with apiKey from settings

### PR DESCRIPTION
**Pull request by aloisbarreras**

### CODE REVIEW

**Comment by aloisbarreras** [comment]
Fixes #30

**Comment by hankim813** [comment]
cc @ccnixon

**Comment by aloisbarreras** [comment]
@ccnixon I updated the original track and orderCompleted test cases to include checking for the app_id. I just added a couple cases to validate that it still works when apiKey is not included in settings as well. Is that what you want?

Sorry if that's a dumb question, just want to make sure I'm addressing what you want :).

**Comment by ccnixon** [comment]
@aloisbarreras - yeah I guess verifying the outgoing payload includes the app_id should suffice. We can try and merge this shortly.

Thanks,
Chris

**Comment by ccnixon** [comment]
Superseded by https://github.com/segment-integrations/integration-appboy/pull/34.

See comment for more info: https://github.com/segment-integrations/integration-appboy/pull/34#issuecomment-291595460

**Pull request closed without merging**
